// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Pantalla login exitoso', function() {

  this.timeout(30000)
  let driver
  
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
  })
  afterEach(async function() {
    await driver.quit();
  })

  it('Pantalla login exitoso', async function() {
    await driver.get("https://katalon-demo-cura.herokuapp.com/")
    await driver.manage().window().setRect({ width: 1260, height: 784 })
    await driver.findElement(By.id("btn-make-appointment")).click()
    await driver.findElement(By.id("txt-username")).sendKeys("John Doe")
    await driver.findElement(By.id("txt-password")).sendKeys("ThisIsNotAPassword")
    await driver.findElement(By.id("btn-login")).click()
    assert(await driver.findElement(By.css(".form-group:nth-child(1) > .col-sm-offset-3")).getText() == "Facility")
  })
})

// JS -> SELECIUM-WEBDRIVER -> DRIVER CHROME (esto es optro programa que necesitamos) -> CHROME